server:
  port: ${SERVER_PORT:8081}

spring:
  profiles.active: @spring.profiles.active@
  application.name: AUI Scholarship Backend Service
  devtools.add-properties: false
  datasource:
    url: jdbc:postgresql://${DATASOURCE_URL}:${DATASOURCE_PORT}/${DATASOURCE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: ${JPA_SHOW_SQL}
    properties.hibernate.jdbc.time_zone: GMT+7
  security:
    oauth2.resourceserver.jwt.issuer-uri: ${keycloak.baseUrl}/realms/aui-scholarship

keycloak:
  clientId: ${KEYCLOAK_CLIENT_SECRET}
  clientSecret: ${KEYCLOAK_CLIENT_SECRET}
  baseUrl: ${KEYCLOAK_BASE_URL}

midtrans:
  merchantId: ${MIDTRANS_MERCHANT_ID}
  serverKey: ${MIDTRANS_SERVER_KEY}
  clientKey: ${MIDTRANS_CLIENT_KEY}
  appBaseUrl: ${MIDTRANS_APPBASE_URL}
  apiBaseUrl: ${MIDTRANS_APIBASE_URL}

imagekit:
  publicKey: ${IMAGEKIT_PUBLIC_KEY}
  privateKey: ${IMAGEKIT_PRIVATE_KEY}
  urlEndpoint: ${IMAGEKIT_URL_ENDPOINT}
  urlUploadEndpoint: https://upload.imagekit.io/api/v1/files/upload
